### ISSUE TITLE
Add integration tests to check if all advertised websites work as intended

### ISSUE THREAD

**Issue by frankMilde** [frankMilde/rol#5]
This is a big check-up, if after so many changes, most websites still work.

This will also serve as a way to establish integration test to automate, if all websites still work.
- [x] <a href="http://www.aeon.co">Aeon</a><br />
- [x]       <a href="http://www.arstechnica.com">Ars Technica</a><br />
- [x]       <a href="http://www.bbc.com">BBC</a><br />
- [x]       <a href="http://www.bbc.com/news">BBC News</a><br />
- [x]       <a href="http://www.bloomberg.com/news">Bloomberg News</a><br />
- [x]       <a href="http://www.codeproject.com">Code Project</a><br />
- [x]       <a href="http://www.drdobbs.com">Dr. Dobb's</a><br />
- [x]       <a href="http://www.evolution-institute.org/article/">Evolution Institute</a><br />
- [x]       <a href="http://www.evolution-institute.org/blog/">Evolution Institute Blog</a><br />
- [x]       <a href="http://www.factmag.com">Fact Magazine</a><br />
- [x]       <a href="http://www.geekwire.com">GeekWire</a><br />
- [x]       <a href="http://magic.wizards.com/en/articles/archive/magic-story">Magic The Gathering -- Story</a><br />
- [ ]       <a href="http://www.heise.de/tp/artikel">Telepolis</a><br />
- [ ]       <a href="https://theintercept.com">The Intercept</a><br />
- [ ]       <a href="http://www.moma.org/explore/inside_out">Inside/Out</a><br />
- [ ]       <a href="http://www.nautil.us/issue">Nautilus Issues</a><br />
- [ ]       <a href="http://www.newyorker.com">The New Yorker</a><br />
- [x]       <a href="http://www.npr.org">National Public Radio</a><br />
- [ ]       <a href="http://www.quantamagazine.org">Quanta Magazine</a><br />
- [ ]       <a href="http://www.research.ibm.com">IBM Research</a><br />
- [ ]       <a href="http://www.serious-science.org">Serious Science</a><br />
- [ ]       <a href="http://www.slate.com">Slate</a><br />
- [ ]       <a href="http://www.techcrunch.com">Techcrunch</a><br />
- [ ]       <a href="http://www.technologyreview.com">MIT Technology Review</a><br />
- [ ]       <a href="http://www.theatlantic.com">The Atlantic</a><br />
- [ ]       <a href="http://www.theguardian.com">The Guardian</a><br />
- [ ]       <a href="http://www.thenewstack.io">The New Stack</a><br />
- [ ]       <a href="http://www.theverge.com">The Verge</a><br />
- [ ]       <a href="http://www.washingtonpost.com">The Washington Post</a><br />
- [ ]       <a href="http://www.wired.com">Wired Magazine</a><br />
